### ISSUE TITLE
init command

### ISSUE THREAD

**Issue by seaneagan** [seaneagan/den#2]
to initialize a pubspec

**Comment by damondouglas** [comment]
@seaneagan Do you mind I give this a try?  If so, which do you think is better?

### simple
`$ den init`

* results in a simple boiler plate pubspec.yaml with each pubspec section [as specified](https://www.dartlang.org/tools/pub/pubspec.html).

### tailored
`$ den init (package | web | server)`

* `den init package` produces a pubspec.yaml for projects intended to be uploaded to pub.
* `den init web` produces a pubspec.yaml for web projects and already include `browser`, `sass`, etc dependencies.
* `den init server` produces a pubspec.yaml for server projects and already include `shelf`, `args`, etc dependencies.

**Comment by seaneagan** [comment]
@damondouglas there is already [stagehand](https://github.com/google/stagehand) for the tailored stuff, and see #5 for how den might be integrated into stagehand.

For `den init` the plan is to use the [prompt](https://github.com/seaneagan/prompt) package to ask the user for each field value.  I want to provide good defaults so the user just has to press enter for most of the questions.  For example, the package name would default to the current directory name, the author can be taken from the user's git config, the version should probably default to `0.1.0`.  Then after all the questions it should output the yaml (preferably with semantic highlighting using the `ansicolor` package) and ask if it looks ok.

If you want to send a PR for something like that, I'd be happy to take a look.

**Comment by damondouglas** [comment]
Hello @seaneagan thank you for letting me give it a go.  My initial attempt so far is creating a `static Pubspec.init` method that fills the `yamlMap['name']` and `yamlMap['version']` values.  I should be sending a PR soon.

**Comment by damondouglas** [comment]
@seaneagan may I trouble you to have an initial look to see if I'm moving in the right direction?

https://github.com/damondouglas/den/commit/56ed2621dc6a075ef9e0e47443a5cd2a81dce090

If all is well, I'll continue with pulling author details from git.config, adding semantic highlighting, and ending confirmation.

**Comment by seaneagan** [comment]
@damondouglas done reviewing that commit, thanks
