### ISSUE TITLE
open ended question about den's scope

### ISSUE THREAD

**Issue by devoncarew** [seaneagan/den#22]
Is it fair to say that den's scope is mostly related to `pubspec.yaml` file manipulation?

I ask because we have a need for reflecting on the packages installed on a user's system; basically parsing the .pubcache into a set of model objects. We're thinking about writing this ourselves, but don't want to duplicate effort. I didn't see anything in the codebase that looked similar to our needs, but wanted to double-check.

@pq @sethladd

**Comment by sethladd** [comment]
Friendly ping.

Looks like den is for manipulating a packagespec.yaml file.

In the meantime, we've created https://github.com/dart-lang/pub_cache

**Comment by seaneagan** [comment]
Yeah, I think `den`'s functionality is restricted to pubspecs, and is more end-user facing (also through [den_api](https://pub.dartlang.org/packages/den_api)), whereas `pub_cache` is not something end-users want to have to worry about as much.  So I think it's good to have separate.  pub_cache looks really useful for tooling stuff, thanks!
