### ISSUE TITLE
Mention den_api package in README

### ISSUE THREAD

**Issue by sethladd** [seaneagan/den#26]
Is there a class that I can import and call methods on?

**Comment by zoechi** [comment]
https://github.com/seaneagan/den_api, https://pub.dartlang.org/search?q=den_api

**Comment by seaneagan** [comment]
@zoechi thanks!

Changing issue to track mentioning den_api in the README.

**Comment by sethladd** [comment]
Oh, it's a separate package. Gotcha. :)
