### ISSUE TITLE
More details on what den bump does

### ISSUE THREAD

**Issue by sethladd** [seaneagan/den#28]
Can you show a before and after in the README? It's not clear what will happen.

```
den bump 1.2.3
den bump patch
den bump major --pre-id beta
den bump release --pre
```

**Comment by sethladd** [comment]
For example, what is a `--pre-id` ?

And will these commands print out what the new version is?

**Comment by seaneagan** [comment]
I was hoping they were self-documenting, but looks like not.

```
den bump 1.2.3 (sets to an exact version)
den bump patch (1.2.3 -> 1.2.4
den bump major --pre-id beta (1.2.3 -> 2.0.0-beta.0)
den bump release --pre (1.2.3 -> 1.2.4-0 or 1.2.3-beta.2 -> 1.2.3-beta.3)
```

I actually have such example text in the `den bump -h` output, but I can copy that over to the README.

A `--pre-id` is a pre-release identifier.  Yes, `den bump ...` does print out both the old and new version.

Let me know if there's anything you don't like about the interface.

**Comment by sethladd** [comment]
thanks! if you can update the readme with those examples, that would help.

**Comment by sethladd** [comment]
Thanks!
