### ISSUE TITLE
Can I bump a plus version?

### ISSUE THREAD

**Issue by sethladd** [seaneagan/den#29]
I'd like to bump `0.0.1+4` to `0.0.1+5`. What is the best way to do that?

**Comment by seaneagan** [comment]
Couldn't remember, so I checked `den bump -h`, and found that it's `den bump build`.  Let me know if that doesn't work for you.

**Comment by sethladd** [comment]
Can you update the readme with this command, and a small note about what it means/does?

Great to see that it exists!

**Comment by sethladd** [comment]
https://github.com/seaneagan/den/pull/30
